### ISSUE TITLE
Implement dashboard interface

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#17]
## 📌 Summary

Extend the deployed Quetz dashboard with the newly designed interfaces for maintainers.

## 📝 Background

This is the frontend counterpart of "Review and add needed Quetz plugins for the backend".

The needed UI elements need to be designed and implemented in the Quetz frontend, following the style guide proposed in the first milestone.

## 🚀 Tasks / Deliverables

- [x] https://github.com/conda-forge/conda-forge.github.io/pull/2090
  - Screencast:

https://github.com/Quansight-Labs/cf-infra-docs/assets/159529/2ba95b2b-378e-4168-9f5b-b088094a7802

## 📅 Estimated completion

This task should be finished in the first [12 months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/2).

**Comment by afshin** [comment]
The status dashboard is ready for review and feedback!

**Comment by jaimergp** [comment]
PR upstream at https://github.com/conda-forge/conda-forge.github.io/pull/2090

**Comment by jaimergp** [comment]
Merged!
