### ISSUE TITLE
Choose / create repository to store WIP documentation

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-conda-forge-mgmt#27]
## 📌 Summary

We need a documentation site to keep track of the audits, infra docs, and other docs or references generated through the grant.
This can then be moved to conda-forge org.

## 🚀 Tasks

- [x] create repo
- [x] set up docs infra - discussed by @jaimergp  and @trallard  to use [Docusaurus](https://docusaurus.io/)
- [x] build site - would suggest using Netlify to get PR previews

**Comment by jaimergp** [comment]
I'd go for `quansight-labs/czi-cf-docs` as the repo name.

**Comment by trallard** [comment]
Done! See https://github.com/Quansight-Labs/czi-cf-docs

**Comment by jaimergp** [comment]
Pushed the initial commit with a basic skeleton. Now we only need to enable Vercel or Netlify. Any preference?
