### ISSUE TITLE
Create preliminar Infrastructure diagrams

### ISSUE THREAD

**Issue by viniciusdc** [Quansight-Labs/czi-conda-forge-mgmt#34]

**Comment by viniciusdc** [comment]
- [ ] Started using diagrams to generate CF bot's components diagrams
  - a brief comparison using javascript-based diagram tooling x python based.
  - Adapt previous docs/graphs/diagrams into new docs structural design

**Comment by viniciusdc** [comment]
After pondering those two approaches, I've decided that Mermaid seems to be the best use case for our docs. The reason can be outlined into two main points:
- The general graph coding experience (layout/classes) is similar to Diagrams, which makes its use quite simple to structure new graphs or add modifications to existing ones
- Docssauros has a built-in (needs import) plugging for including mermaid diagrams direct in markdown files without much trouble. e.g.
```mermaid
... your diagram here
```
In compression with Diagram it is easier to handle, build (no need to run extra commands), and modify in the future.

**Comment by viniciusdc** [comment]
As of now, to reduce the spent time on getting our diagram in the mermaid format, we will be using LucidCharts to generate the structure of these, for initial review and iterations, and later import into the docs with the proper formating/code

**Comment by viniciusdc** [comment]
Current iteration 
![image](https://user-images.githubusercontent.com/51954708/221872665-02ea8443-ce13-4b32-89cc-83ee99db4a96.png)

**Comment by viniciusdc** [comment]
Here we have come key concepts described using different colors:
- Agents/actors
- Objects
- Verbs
which still lack a proper definition, but its idea is to better organize the different situations and functionality of conda-forge infrastructure into classes of objects that sometimes interact with other resources (usually modifying some integral part of it), the agents/actors, or the object that receive such interactions "the objects."

Such classification helps outline the different scenarios with which the same object/actor might be involved and the extra level of coordination/management/authority that the same object controls.

- Identified above the core concept is definitely the feedstock, wich in the next iteration will become the center part of the next diagrams in a more easy to read/follow representation

**Comment by jaimergp** [comment]
I merged the current status to get us going but we need to revisit the diagrams in the future. I'll create a separate issue for that.
